### ISSUE TITLE
have an example ? get nan error 

### ISSUE THREAD

**Issue by luolaihu** [CNevd/DiFacto2_ffm#2]
output:
[17:03:55] src/main.cc:40:  - l1_shrk = 0
[17:03:55] src/main.cc:71: start run learner
[17:03:55] src/sgd/sgd_learner.cc:80: Start epoch 0
    1          0        0 |         0 |   -nan     -nan 
    2          0        0 |         0 |   -nan     -nan 
    3          0        0 |         0 |   -nan     -nan 
    4          0        0 |         0 |   -nan     -nan 
    5          0        0 |         0 |   -nan     -nan 
    6          0        0 |         0 |   -nan     -nan 
    7          0        0 |         0 |   -nan     -nan 
    8          0        0 |         0 |   -nan     -nan 
    9          0        0 |         0 |   -nan     -nan 
   10          0        0 |         0 |   -nan     -nan 
   11          0        0 |         0 |   -nan     -nan 
   12          0        0 |         0 |   -nan     -nan 
   13          0        0 |         0 |   -nan     -nan 
   14          0        0 |         0 |   -nan     -nan 
   15          0        0 |         0 |   -nan     -nan 
   16          0        0 |         0 |   -nan     -nan 
   17      1e+04    1e+04 |         0 | 0.6931  0.55892 
local.conf:
# data
data_in = /data/data1/ffm/data/train.data
data_val = /data/data1/ffm/data/test.data

# learner
learner = sgd
max_num_epochs = 2
batch_size = 10000
field_num=68

V_dim = 2
has_aux=1
l1_shrk=0

**Comment by CNevd** [comment]
will add an example tonight：） @qiang2008
